### ISSUE TITLE
Redhat/CentOS 7 support (compile from source)

### ISSUE THREAD

**Issue by mejo-** [mrlesmithjr/ansible-samba#13]
Unfortunately, Redhat/CentOS 7 don't ship `samba-tool`. That's why compiling Samba from source is the only option when you want to use `samba-tool` for maintaining your AD directory controller on those systems.

I have some WIP patches for the role to add support for compiling (and upgrading) Samba from source. Unfortunately, they're quite invasive. You can find them at https://github.com/mejo-/ansible-samba/commit/e13e9f60934e024b0868345ae56745dc44aa57b1

The patch is currently applied against `darrylweaver/ansible-samba`, but I would prefer to implement it in your role as it seems to be more actively used and it's upstream to `darrylweaver/ansible-samba` anyway.

Would you consider to apply such a patch or is it too intrusive for you?

**Comment by thiagogomesverissimo** [comment]
I have done similar work to build samba from source in debian/ubuntu distros. (it is not well documented yet)

https://github.com/uspdev/ansible-role-install-samba

I can bring this code to this role too.

**Comment by mejo-** [comment]
@thiagogomesverissimo thanks for sharing your code. Things that came into my mind while skimming through your code:

* It's specific to Debian and doesn't support Redhat based systems (yet)
* On Debian, it lists all build-dependencies manually instead of using the `build-depends` option to the Ansible apt module

Apart from that, it's pretty similar, only that it's not integrated into the role logic yet. I don't have strong feelings on which code to use, but adding support for compiling from source to this role would be very nice in any case :)

**Comment by mrlesmithjr** [comment]
I would be very interested in seeing what you guys can come up with in regards to this. We would need to have some good testing results to validate with and etc. as well. But I think this would be very very useful to this role.

**Comment by mejo-** [comment]
I prepared a merge request: #16 

Let me know what you think about it. Would be awesome to get this merged :)
