### ISSUE TITLE
Add support for provisioning backup AD domain controllers

### ISSUE THREAD

**Issue by mejo-** [mrlesmithjr/ansible-samba#14]
It would be nice to be able to provision backup AD domain controllers using this role. So far, the role only allows to join a domain as 'MEMBER', not as backup DC.

I patched the role to differ between `samba_dc_role` `primary` and `secondary`: https://github.com/mejo-/ansible-samba/commit/e4fd4ab7fa3cd924594a7a281a1b7d3e3d788e48

@mrlesmithjr: Would you consider to merge this patch into your role? If so, then I'll prepare a merge request.

**Comment by mejo-** [comment]
Ok, sorry for the noise. Just realized that your role already has full support for provisioning backup AD domain controllers. I worked on `darrylweaver/ansible-samba` (which is a fork of your role) and accidently expected that they were similar in this regard. Good to learn that they're not :)

**Comment by mrlesmithjr** [comment]
Awesome and no worries
