### ISSUE TITLE
Don't mark domain as created on secondary directory controllers

### ISSUE THREAD

**Issue by mejo-** [mrlesmithjr/ansible-samba#15]
The current logic to touch `/var/log/.samba_ad_created` in [`tasks/create_domain.yml`](https://github.com/mrlesmithjr/ansible-samba/blob/29a70c9114f7dba047780d99375e544f0dd305a6/tasks/create_domain.yml#L42-L65) breaks provisioning of secondary directory controllers without provisioning the primary DC at the same time.

The problematic code is in [line 54](https://github.com/mrlesmithjr/ansible-samba/blob/29a70c9114f7dba047780d99375e544f0dd305a6/tasks/create_domain.yml#L54). `hostvars[samba_primary_domain_controller]['_samba_domain_exists']` will not be set when Ansible didn't run the preceding tasks on the primary DC as well.

I suggest to drop the whole last three tasks ins `tasks/create_domain.yml`. At least I didn't understand what the purpose of touching `/var/log/.samba_ad_created` on secondary DSs is at all. On the primary DC, it's already touched earlier in task [`create_domain | marking domain as created`](https://github.com/mrlesmithjr/ansible-samba/blob/29a70c9114f7dba047780d99375e544f0dd305a6/tasks/create_domain.yml#L31-L40).

**Comment by mrlesmithjr** [comment]
@mejo- Hey man! The idea was to ensure that if for some reason the secondaries were not marked, then we could potentially run into an issue. So, maybe I am not really understanding what issue you ran into. But I am definitely open to adjusting this if it makes absolute sense. Thanks for the input.
