### ISSUE TITLE
Need to be able to have support for home directories.

### ISSUE THREAD

**Issue by wb8tyw** [mrlesmithjr/ansible-samba#23]
Tried to use this to setup a simple samba server needed:

1. A read-only public share.  That worked good, but would prefer to have the option of a overriding the "samba_share_path" on a per share basis.

2. Read/write shares for the /home directory of the users with logon privileges.
No support in this role for doing that.

**Comment by wb8tyw** [comment]
Locally hacked by adding this to the smb.conf.j2 file:

{% if samba_home_shares is defined and samba_home_shares %}
[home]
browsable = yes
guest ok = no
path = /home/%u
writable = yes
{% endif %}

**Comment by mrlesmithjr** [comment]
@wb8tyw Thanks for reporting this. PR's are welcomed if interested.
