### ISSUE TITLE
Not restart smbd and smbd directly

### ISSUE THREAD

**Issue by thiagogomesverissimo** [mrlesmithjr/ansible-samba#9]
From https://wiki.samba.org/index.php/Managing_the_Samba_AD_DC_Service_Using_Systemd

> ... the /usr/local/samba/sbin/samba service automatically starts the required smbd and winbindd service as sub-processes. If you start them manually, the Samba DC fails to work as expected. If your package provider created additional Samba service files, disable and mask them to prevent that other services re-enable them...

**Comment by mrlesmithjr** [comment]
@thiagogomesverissimo I need to do some testing on this. My assumption is that if samba is configured to provide AD services this may be fine however, if not then the individual services being restarted may still be applicable.

#11

**Comment by thiagogomesverissimo** [comment]
Yes, this point should be better tested. 
In this role, I can be wrong, but samba is always configured to be a domain controller, a new one or a join. And, I noted in new samba versions, when restart smbd and nmbd in DC server , errors are thrown saying we must restart samba-ad-dc, insted. I will do more tests anyway.
